on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/mwoodbri/jekyll-gh-pages-docker:main
      - run: ls -a
#     - uses: JamesIves/github-pages-deploy-action@3
#       with:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         BRANCH: gh-pages
#         FOLDER: _site
#     - uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: _site
        
